environment: "localhost"
host: 0.0.0.0
port: 4000
protocol: "http"

authentication:
  protect_routes: true

dbConfiguration:
  host: "containers-us-west-137.railway.app"
  port: 5952
  username: "root"
  password: "fUvYQk5jiILKx9v7oOEI"
  database: "railway"
